### ISSUE TITLE
not all nodes are fetched

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/vgrid#10]
```
despiegk1@kristofleersmbp examples % v run /Users/despiegk1/.vmodules/threefoldtech/vgrid/examples/get_nodes_by_capacity.v  | more
found 50 nodes with following min resources:
```
we  should get upto e.g. 1000 nodes and if above, give error, otherwise people do not know they have them all
we should in client do the paging per 100 or so

this query is ofcourse not limited to 50

**Comment by sameh-farouk** [comment]
This is because (inherited from the API call) the results for paginated objects default to page=1, size=50 if these fields were omitted.

so to get the second page you need to pass `page: 2` to the get_nodes client method. and increase it till you get all available pages.

we can add to the client a higher-level function to simplify this, that returns an iterator-like struct, that have next method to query for first/next page, so i suggest something similar to
```v
nodes_iter := gp_client.get_nodes_iter(optioanl_filter)?
nodes_p1 = nodes_iter.next() // nodes of first page
nodes_p2 = nodes_iter.next() // nodes of second page
nodes_p3 = nodes_iter.next() // etc
```
then a script or application can use this `iter` to get all nodes if needed. by calling next() and appending the nodes to a list in a loop, till next() returns an empty list which means we reached the end. also, the for loop in v now supports iterators.

```v
for nodes in nodes_iter {
	println(nodes)
        // appending it to a list and do other stuff
}
```
also, note that this script is just an example, with no specific requirements or real-world usage scenario in mind to provide a template that could be edited to satisfy specific needs. so if you have other expectations besides that from these scripts please clarify.

**Comment by sameh-farouk** [comment]
**Update:**

I have implemented Iterators for nodes, gateways, farms, contracts, and twins. the client code was refactored, and example scripts were updated. squashed a bug too :)

Now example scripts will try to consume all available nodes, you can limit the number of nodes returned by passing `--max-count <NUM>`. also `--netwrok <NET>` and `--cache` was added to enhance the example scripts.

can you check now? 

![Screenshot from 2022-06-28 15-13-59](https://user-images.githubusercontent.com/42457449/176187666-f6184df9-f8c7-4122-ae09-2bab02c78bab.png)

**Comment by despiegk** [comment]
its nice we did this, but maybe in future lets keep things more simple
this is an example where we try to do sooo good that things get more complicated than they should be

it would have been easier and using way less resources to just return 1000 results by default on the rest server, no code would have to be changed here, also paging we don't need in a client
it makes things much more complicated than it should


anyhow the example is not working see next comment

**Comment by despiegk** [comment]
see #10
